pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
}
    
    stages {
        
        stage('Checkout'){
           steps {
        sh 'echo passed'
        //git branch: 'main', url: 'https://github.com/shubhamgit7/Jenkins-Zero-To-Hero.git'
      }
        }
        stage('Static Code Analysis') {
      environment {
        SONAR_URL = "http://18.193.48.28:9000"
      }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh 'cd python-jenkins-argocd-k8s'
                    echo 'Buid Docker Image'
                    docker build -t shubhamgadgil/cicd-e2e:${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push shubhamgadgil/cicd-e2e:${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'f87a34a8-0e09-45e7-b9cf-6dc68feac670', 
                url: 'https://github.com/shubhamgit7/cicd-demo-manifests-repo.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([string(credentialsId: 'github', variable: 'GITHUB_TOKEN')]) {
                        sh '''
                        cat deploy.yaml
                        sed -i '' "s/32/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/shubhamgit7/cicd-demo-manifests-repo.git HEAD:main
                        '''                        
                    }
                }
            }
        }
    }
}
